{% set version = '1.0.0-rc3' %}
{% set posix = 'm2-' if win else '' %}
package:
  name: r-rcppplanc
  version: {{ version|replace("-", "_") }}
source:
  patches:
    - patches/remove-hardcoded-dep-path.patch
    - patches/add-cxx-libc-availability.patch    # [not win]
    - patches/Windows-explicit-options.patch  # [win]
  url: https://github.com/welch-lab/RcppPlanc/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8d484a27815b02d512e729cfc8f59ace35e17f7062ff114fd9476b74f15453b0
build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - {{ stdlib("c") }}  # [not win]
    - {{ stdlib("m2w64_c") }}  # [win]
    - cmake >=3.22
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [not osx]
    - pkg-config
    - {{ posix }}diffutils
    - {{ posix }}patch
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - libhwloc >=2.0.0,<3.0.0
    - zlib
    - hdf5 >=1.10
    - llvm-openmp  # [osx]
    - libgomp  # [not osx]
    - libblas
    - libcblas
    - liblapack
    - highfive <3
    - dlfcn-win32  # [win]

  run:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - libblas  # [not (osx and arm64)]
    - libblas * *accelerate  # [osx and arm64]
    - libgomp  # [win]
test:
  commands:
    - $R -e "library('RcppPlanc')"           # [not win]
    - "\"%R%\" -e \"library('RcppPlanc')\""  # [win]
about:
  home: https://github.com/welch-lab/rcppplanc
  license: GPL-2.0-or-later
  summary: '''Rcpp'' bindings for ''PLANC'', a highly parallel and extensible NMF/NTF  (Non-negative
    Matrix/Tensor Factorization) library. Wraps algorithms described in Kannan et. al
    (2018) <doi:10.1109/TKDE.2017.2767592> and Eswar et. al (2021) <doi:10.1145/3432185>.
    Implements algorithms described in Welch et al. (2019) <doi:10.1016/j.cell.2019.05.006>,
    Gao et al. (2021) <doi:10.1038/s41587-021-00867-x>, and Kriebel & Welch (2022) <doi:10.1038/s41467-022-28431-4>.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
extra:
  recipe-maintainers:
    - theAeon
    - conda-forge/r
