schema_version: 1

context:
  version: "2.0.5"

package:
  name: r-rcppplanc
  version: ${{ version|replace("-", "_") }}

source:
  url: https://github.com/welch-lab/RcppPlanc/archive/refs/tags/${{ version }}.tar.gz
  sha256: 42302a7add85cf030aada1b73132d3dfba9129ae8a94e999132e131471fc10c3
  patches:
    - patches/remove-hardcoded-dep-path.patch
    - if: win
      then: patches/Windows-explicit-options.patch
      else: patches/add-cxx-libc-availability.patch
    - if: osx and arm64
      then: patches/osx-arm-find-r.patch
    - if: linux and build_platform != target_platform
      then: patches/linux-cc-r-link.patch

build:
  number: 0
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/
    missing_dso_allowlist:
      - if: win
        then:
          - "*/R.dll"
          - "*/Rblas.dll"
          - "*/Rlapack.dll"

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - cross-r-base ${{ r_base }}
        - r-rcppprogress
        - r-rcpp
        - r-rcpparmadillo
        - r-matrix
    - if: unix
      then:
        - gnuconfig
        - git
        - diffutils
        - patch
    - if: not win
      then:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
      else:
        - ${{ compiler('m2w64_c') }}
        - ${{ stdlib("m2w64_c") }}
        - ${{ compiler('m2w64_cxx') }}
        - m2-filesystem
        - m2-zip
        - m2-diffutils
        - m2-patch
    - if: osx
      then: llvm-openmp
      else: libgomp
    - cmake >=3.22
    - make
    - pkg-config
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - libhwloc >=2.0.0,<3.0.0
    - zlib
    - hdf5 >=1.10
    - if: osx
      then: llvm-openmp
      else: libgomp
    - libblas
    - libcblas
    - liblapack
    - highfive <3
    - if: win
      then: dlfcn-win32
  run:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - if: osx and arm64
      then: libblas * *accelerate
      else: libblas
    - if: win
      then: libgomp

tests:
  - script:
      - if: win
        then: Rscript -e \"library('RcppPlanc')\"
        else: Rscript -e \"library\('RcppPlanc'\)\"

about:
  license: GPL-2.0-or-later
  summary: '''Rcpp'' bindings for ''PLANC'', a highly parallel and extensible NMF/NTF  (Non-negative Matrix/Tensor Factorization) library. Wraps algorithms described in Kannan et. al (2018) <doi:10.1109/TKDE.2017.2767592> and Eswar et. al (2021) <doi:10.1145/3432185>. Implements algorithms described in Welch et al. (2019)
    <doi:10.1016/j.cell.2019.05.006>, Gao et al. (2021) <doi:10.1038/s41587-021-00867-x>, and Kriebel & Welch (2022) <doi:10.1038/s41467-022-28431-4>.'
  license_file:
    - LICENSE-GPL.md
  homepage: https://github.com/welch-lab/rcppplanc

extra:
  recipe-maintainers:
    - theAeon
    - conda-forge/r
